# Generated by Django 4.2.5 on 2024-04-25 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='note_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(max_length=100)),
                ('year_of_release', models.IntegerField()),
                ('duration', models.TextField()),
                ('cast', models.CharField(max_length=100)),
                ('crew', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
